# Generated by Django 2.2 on 2020-02-27 20:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('title', models.CharField(max_length=32, unique=True, verbose_name='乙方公司')),
                ('ein_no', models.CharField(max_length=18, verbose_name='税号')),
                ('address', models.CharField(max_length=64, verbose_name='地址')),
                ('tel', models.CharField(max_length=13, verbose_name='电话')),
                ('bank_name', models.CharField(max_length=32, verbose_name='开户银行')),
                ('bank_account', models.CharField(max_length=32, verbose_name='银行账号')),
            ],
            options={
                'verbose_name': '公司名称',
                'verbose_name_plural': '公司名称',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=12, verbose_name='姓名')),
                ('gender', models.IntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别')),
                ('tel', models.CharField(max_length=24, verbose_name='直线号码')),
                ('phone', models.CharField(max_length=12, verbose_name='手机号码')),
                ('email', models.EmailField(max_length=254, verbose_name='电子邮箱')),
                ('wechat_name', models.CharField(max_length=64, verbose_name='微信')),
                ('meno', models.TextField(max_length=256, verbose_name='联系人备注信息')),
                ('address', models.CharField(max_length=128, verbose_name='送货地址')),
                ('invoice_address', models.CharField(max_length=128, verbose_name='发票地址')),
            ],
            options={
                'verbose_name': '联系人',
                'verbose_name_plural': '联系人',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='客户名称')),
                ('tel', models.CharField(max_length=24, unique=True, verbose_name='公司电话')),
                ('website', models.CharField(max_length=64, verbose_name='公司网址')),
                ('ein', models.CharField(max_length=18, verbose_name='税号')),
                ('bank', models.CharField(max_length=18, verbose_name='银行')),
                ('bank_account', models.CharField(max_length=32, verbose_name='银行帐号')),
                ('address_tel', models.CharField(max_length=128, verbose_name='地址电话')),
                ('image', models.ImageField(default='media/customer/default.jpg', upload_to='media/customer/%Y')),
            ],
            options={
                'verbose_name': '客户信息',
                'verbose_name_plural': '客户信息',
            },
        ),
        migrations.CreateModel(
            name='Delivery_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('title', models.CharField(max_length=32, verbose_name='发货时间')),
            ],
            options={
                'verbose_name': '发货时间',
                'verbose_name_plural': '发货时间',
            },
        ),
        migrations.CreateModel(
            name='Delivery_way',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('title', models.CharField(max_length=32, verbose_name='发货方式')),
            ],
            options={
                'verbose_name': '发货方式',
                'verbose_name_plural': '发货方式',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='货品名称')),
                ('nickname', models.CharField(blank=True, max_length=64, null=True, verbose_name='别名')),
                ('price', models.FloatField(default=0, verbose_name='采购价')),
                ('date', models.DateField(auto_now=True, verbose_name='更改日期')),
                ('meno', models.TextField(default='备注信息', verbose_name='备注')),
            ],
            options={
                'verbose_name': '货品资料',
                'verbose_name_plural': '货品资料',
            },
        ),
        migrations.CreateModel(
            name='Position_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=12, verbose_name='职务')),
            ],
            options={
                'verbose_name': '职务',
                'verbose_name_plural': '职务',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('title', models.CharField(max_length=32, verbose_name='发票税率')),
            ],
            options={
                'verbose_name': '发票税率',
                'verbose_name_plural': '发票税率',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='服务')),
            ],
            options={
                'verbose_name': '服务政策',
                'verbose_name_plural': '服务政策',
            },
        ),
        migrations.CreateModel(
            name='Terms_of_payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='付款方式')),
            ],
            options={
                'verbose_name': '服务政策',
                'verbose_name_plural': '服务政策',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=24, verbose_name='货品类别')),
            ],
            options={
                'verbose_name': '货品类别',
                'verbose_name_plural': '货品类别',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=24, verbose_name='单位')),
            ],
            options={
                'verbose_name': '货品单位',
                'verbose_name_plural': '货品单位',
            },
        ),
        migrations.CreateModel(
            name='Validity_period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('title', models.CharField(default=0, max_length=32, verbose_name='有效期')),
            ],
            options={
                'verbose_name': '有效期',
                'verbose_name_plural': '有效期',
            },
        ),
        migrations.CreateModel(
            name='Warranty_policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='保修政策')),
            ],
            options={
                'verbose_name': '保修政策',
                'verbose_name_plural': '保修政策',
            },
        ),
        migrations.CreateModel(
            name='Quotation_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('qid', models.CharField(max_length=24, unique=True, verbose_name='单据编号')),
                ('meno', models.TextField(max_length=256, verbose_name='备注信息')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.Contact', verbose_name='联系人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.Customer', verbose_name='客户名称')),
                ('delivery_time', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='quotation.Delivery_time', verbose_name='交货时间')),
                ('delivery_way', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='quotation.Delivery_way', verbose_name='交货方式')),
                ('rate', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='quotation.Rate', verbose_name='税率')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.Service', verbose_name='服务条款')),
                ('terms_of_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.Terms_of_payment', verbose_name='付款方式')),
                ('validity_period', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='quotation.Validity_period', verbose_name='有效期')),
                ('warranty_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.Warranty_policy', verbose_name='保修政策')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quotation_goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('count', models.IntegerField(default=1, verbose_name='数量')),
                ('price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='单价')),
                ('meno', models.CharField(max_length=64, verbose_name='备注')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='quotation.Quotation_info', verbose_name='订单')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.Goods', verbose_name='货品名称')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='gtype',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='quotation.Type', verbose_name='货品类别'),
        ),
        migrations.AddField(
            model_name='goods',
            name='unit',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='quotation.Unit', verbose_name='单位'),
        ),
        migrations.AddField(
            model_name='contact',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.Customer', verbose_name='所在公司'),
        ),
        migrations.AddField(
            model_name='contact',
            name='position',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='quotation.Position_type', verbose_name='职务'),
        ),
    ]
