# Generated by Django 2.2 on 2020-03-27 21:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='品牌')),
            ],
            options={
                'verbose_name': '品牌',
                'verbose_name_plural': '品牌',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('title', models.CharField(max_length=32, unique=True, verbose_name='乙方公司')),
                ('ein_no', models.CharField(max_length=18, verbose_name='税号')),
                ('address', models.CharField(max_length=64, verbose_name='地址')),
                ('tel', models.CharField(max_length=13, verbose_name='电话')),
                ('bank_name', models.CharField(max_length=32, verbose_name='开户银行')),
                ('bank_account', models.CharField(max_length=32, verbose_name='银行账号')),
            ],
            options={
                'verbose_name': '公司名称',
                'verbose_name_plural': '公司名称',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=12, verbose_name='姓名')),
                ('gender', models.IntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别')),
                ('tel', models.CharField(max_length=24, verbose_name='直线号码')),
                ('phone', models.CharField(max_length=12, verbose_name='手机号码')),
                ('email', models.EmailField(max_length=254, verbose_name='电子邮箱')),
                ('wechat_name', models.CharField(max_length=64, verbose_name='微信')),
                ('meno', models.TextField(max_length=256, verbose_name='联系人备注信息')),
                ('address', models.CharField(max_length=128, verbose_name='送货地址')),
                ('invoice_address', models.CharField(max_length=128, verbose_name='发票地址')),
            ],
            options={
                'verbose_name': '联系人',
                'verbose_name_plural': '联系人',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='客户名称')),
                ('tel', models.CharField(max_length=24, unique=True, verbose_name='公司电话')),
                ('website', models.CharField(max_length=64, verbose_name='公司网址')),
                ('ein', models.CharField(max_length=18, verbose_name='税号')),
                ('bank', models.CharField(max_length=18, verbose_name='银行')),
                ('bank_account', models.CharField(max_length=32, verbose_name='银行帐号')),
                ('address_tel', models.CharField(max_length=128, verbose_name='地址电话')),
                ('image', models.ImageField(default='media/customer/default.jpg', upload_to='media/customer/%Y')),
            ],
            options={
                'verbose_name': '客户信息',
                'verbose_name_plural': '客户信息',
            },
        ),
        migrations.CreateModel(
            name='Delivery_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('title', models.CharField(max_length=32, verbose_name='发货时间')),
            ],
            options={
                'verbose_name': '发货时间',
                'verbose_name_plural': '发货时间',
            },
        ),
        migrations.CreateModel(
            name='Delivery_way',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('title', models.CharField(max_length=32, verbose_name='发货方式')),
            ],
            options={
                'verbose_name': '发货方式',
                'verbose_name_plural': '发货方式',
            },
        ),
        migrations.CreateModel(
            name='Position_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=12, verbose_name='职务')),
            ],
            options={
                'verbose_name': '职务',
                'verbose_name_plural': '职务',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('title', models.CharField(max_length=32, verbose_name='发票税率')),
            ],
            options={
                'verbose_name': '发票税率',
                'verbose_name_plural': '发票税率',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='服务')),
            ],
            options={
                'verbose_name': '服务政策',
                'verbose_name_plural': '服务政策',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='供应商')),
                ('tel', models.CharField(max_length=24, verbose_name='公司电话')),
                ('contact', models.CharField(max_length=64, verbose_name='联系人')),
                ('phone', models.CharField(max_length=13, verbose_name='联系手机')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
            },
        ),
        migrations.CreateModel(
            name='Terms_of_payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='付款方式')),
            ],
            options={
                'verbose_name': '付款方式',
                'verbose_name_plural': '付款方式',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=24, verbose_name='货品类别')),
            ],
            options={
                'verbose_name': '货品类别',
                'verbose_name_plural': '货品类别',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=24, verbose_name='单位')),
            ],
            options={
                'verbose_name': '货品单位',
                'verbose_name_plural': '货品单位',
            },
        ),
        migrations.CreateModel(
            name='Validity_period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('title', models.CharField(default=0, max_length=32, verbose_name='有效期')),
            ],
            options={
                'verbose_name': '有效期',
                'verbose_name_plural': '有效期',
            },
        ),
        migrations.CreateModel(
            name='Warranty_policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='保修政策')),
            ],
            options={
                'verbose_name': '保修政策',
                'verbose_name_plural': '保修政策',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gmodel', models.CharField(default='', max_length=64, unique=True, verbose_name='品名规格')),
                ('price', models.FloatField(default=0, verbose_name='进价')),
                ('min_price', models.FloatField(default=0, verbose_name='最低售价')),
                ('meno', models.TextField(default='备注信息', verbose_name='备注')),
                ('date', models.DateField(auto_now=True, verbose_name='更改日期')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.Brand', verbose_name='品牌')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.Supplier', verbose_name='供应商')),
                ('type', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='quotation.Type', verbose_name='分类')),
                ('unit', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='quotation.Unit', verbose_name='单位')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品信息',
            },
        ),
    ]
