# Generated by Django 2.2 on 2020-02-27 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='gtype',
            new_name='type',
        ),
    ]
