# Generated by Django 2.2 on 2020-03-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0002_auto_20200327_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='tel',
        ),
        migrations.AddField(
            model_name='supplier',
            name='advantage',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='优势品牌'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='meno',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='联系信息'),
        ),
    ]
