# Generated by Django 2.2 on 2020-02-28 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0002_auto_20200227_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation_info',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='quotation_info',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='quotation_info',
            name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='quotation_info',
            name='delivery_way',
        ),
        migrations.RemoveField(
            model_name='quotation_info',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='quotation_info',
            name='service',
        ),
        migrations.RemoveField(
            model_name='quotation_info',
            name='terms_of_payment',
        ),
        migrations.RemoveField(
            model_name='quotation_info',
            name='validity_period',
        ),
        migrations.RemoveField(
            model_name='quotation_info',
            name='warranty_policy',
        ),
        migrations.DeleteModel(
            name='Quotation_goods',
        ),
        migrations.DeleteModel(
            name='Quotation_info',
        ),
    ]
