# Generated by Django 2.2 on 2020-03-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0003_auto_20200327_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='meno',
            field=models.TextField(blank=True, default='备注信息', null=True, verbose_name='备注'),
        ),
    ]
