# Generated by Django 2.2 on 2020-02-28 00:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotation', '0003_auto_20200228_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('qid', models.CharField(max_length=24, unique=True, verbose_name='单据编号')),
                ('meno', models.TextField(max_length=256, verbose_name='备注信息')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.Contact', verbose_name='联系人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.Customer', verbose_name='客户名称')),
                ('delivery_time', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='quotation.Delivery_time', verbose_name='交货时间')),
                ('delivery_way', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='quotation.Delivery_way', verbose_name='交货方式')),
                ('rate', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='quotation.Rate', verbose_name='税率')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.Service', verbose_name='服务条款')),
                ('terms_of_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.Terms_of_payment', verbose_name='付款方式')),
                ('validity_period', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='quotation.Validity_period', verbose_name='有效期')),
                ('warranty_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.Warranty_policy', verbose_name='保修政策')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quotation_goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('count', models.IntegerField(default=1, verbose_name='数量')),
                ('price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='单价')),
                ('meno', models.CharField(max_length=64, verbose_name='备注')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='documents.Quotation_info', verbose_name='订单')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.Goods', verbose_name='货品名称')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
