# Generated by Django 2.2 on 2020-03-27 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotation', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation_info',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.Contact', verbose_name='联系人'),
        ),
        migrations.AddField(
            model_name='quotation_info',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.Customer', verbose_name='客户名称'),
        ),
        migrations.AddField(
            model_name='quotation_info',
            name='delivery_time',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='quotation.Delivery_time', verbose_name='交货时间'),
        ),
        migrations.AddField(
            model_name='quotation_info',
            name='delivery_way',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='quotation.Delivery_way', verbose_name='交货方式'),
        ),
        migrations.AddField(
            model_name='quotation_info',
            name='rate',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='quotation.Rate', verbose_name='税率'),
        ),
        migrations.AddField(
            model_name='quotation_info',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.Service', verbose_name='服务条款'),
        ),
        migrations.AddField(
            model_name='quotation_info',
            name='terms_of_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.Terms_of_payment', verbose_name='付款方式'),
        ),
        migrations.AddField(
            model_name='quotation_info',
            name='validity_period',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='quotation.Validity_period', verbose_name='有效期'),
        ),
        migrations.AddField(
            model_name='quotation_info',
            name='warranty_policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.Warranty_policy', verbose_name='保修政策'),
        ),
        migrations.AddField(
            model_name='quotation_goods',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='documents.Quotation_info', verbose_name='订单'),
        ),
        migrations.AddField(
            model_name='quotation_goods',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.Goods', verbose_name='货品名称'),
        ),
    ]
